baseURL = "https://lokal.ninja/schleswig-holstein"
languageCode = "de-DE"
title = "Lokal Ninja - Schleswig-Holstein"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Schleswig-Holstein"
  repo = "schleswig-holstein"
